# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ self, inputs, ... }:
{
  flake.nixosModules.DesktopHardwareConfig =

    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:

    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/mapper/luks-c6d216ab-1bd0-4014-bcc5-20edca3dcc8c";
        fsType = "btrfs";
      };

      boot.initrd.luks.devices."luks-c6d216ab-1bd0-4014-bcc5-20edca3dcc8c".device =
        "/dev/disk/by-uuid/c6d216ab-1bd0-4014-bcc5-20edca3dcc8c";

      fileSystems."/home" = {
        device = "/dev/mapper/luks-c6d216ab-1bd0-4014-bcc5-20edca3dcc8c";
        fsType = "btrfs";
        options = [ "subvol=home" ];
      };

      fileSystems."/nix" = {
        device = "/dev/mapper/luks-c6d216ab-1bd0-4014-bcc5-20edca3dcc8c";
        fsType = "btrfs";
        options = [ "subvol=nix" ];
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/99DE-834C";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [
        { device = "/dev/disk/by-uuid/84b50344-117d-4652-9b5d-3376268068b1"; }
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
